"""Create verify contact token table

Revision ID: 1a24cc1e868d
Revises: b5b1585bba1a
Create Date: 2025-06-30 22:33:57.604700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a24cc1e868d'
down_revision: Union[str, None] = 'b5b1585bba1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_contact_token',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('date_use', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verify_contact_token_uuid'), 'verify_contact_token', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verify_contact_token_uuid'), table_name='verify_contact_token')
    op.drop_table('verify_contact_token')
    # ### end Alembic commands ###
