"""Create contact table

Revision ID: e582ee62d86e
Revises: afe9eb361832
Create Date: 2025-06-08 12:08:21.248947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e582ee62d86e'
down_revision: Union[str, None] = 'afe9eb361832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('contact_type', sa.Enum('PHONE', 'EMAIL', 'TELEGRAM', 'WHATSAPP', 'VK', 'SITE', 'OTHER', name='contacttype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('date_verify', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_uuid'), 'contact', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_uuid'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
